# Settings for ros_control control loop
hardware_control_loop:
  loop_hz: &loop_hz 10

# Settings for ros_control hardware interface
hardware_interface:
  joints: &robot_joints
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

# Pass an array of joint position directly to the joints
# Default, do nothing
joint_group_pos_controller:
  type: position_controllers/JointGroupPositionController
  joints: *robot_joints

# Pass an array of joint velocities directly to the joints
joint_group_vel_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints: *robot_joints
