sensors:
  - filtered_cloud_topic: filtered_cloud
    max_range: 2.5
    max_update_rate: 0.5
    padding_offset: 0.01
    padding_scale: 1.0
    point_cloud_topic: /rgbd_common/depth/points
    point_subsample: 1
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
